### ISSUE TITLE
Haskell for filtered tags

### ISSUE THREAD

**Issue by fxfactorial** [Abizern/hblog#4]
I'm having a hard time coming up with the needed haskell changes to the hblog.hs file so that I get an atom.xml populated only by a specific tag, ie I want an atom.xml that only lists my `ocaml` tagged posts, can you help you preferably with code? 

I tried doing this: https://github.com/fxfactorial/hblog/blob/master/hblog.hs#L14 but that apparently isn't enough and I don't know haskell or hakyll well enough to dig into it. 

Thank you.

**Comment by fxfactorial** [comment]
@Abizern if this is too much of a hassle then let me know, maybe better to just close this issue?

**Comment by Abizern** [comment]
It’s not too much hassle, it’s something I’d like to do for myself, I just haven’t managed to get around to it yet.

## Thanks for reminding me.

Abizer

**Comment by fxfactorial** [comment]
@Abizern thank you, I would greatly appreciate it.

**Comment by Abizern** [comment]
I'm closing this as I haven't used or maintained the Hakyll generated blog in a long time, so I'm unlikely to do this.
